/*
    Maryam Yassir
    Number Guessing Game 
    This mini program will create a small game where the user will try to guess a random number 
    generated by the computer

    
    1. Have the code generate a number 
        1.1 Use math.random to generate a number from 1 - 100
    2. Prompt the user to input a number
        2.1 Use a scanner to get number input
    3. Check if the input number is the same as the generated number
        3.1 have it check in a loop until the correct number is guessed
*/

//import
import java.util.Scanner;

public class NumberGuessingGame
{
    public static void main(String args[])
    {
        //variables
	    int randomNum = (int)(Math.random() * 10) + 1;
	    int inputNum;
	
	    //Scanner
	    Scanner myScanner = new Scanner(System.in);
	
	    //Prompting the user to input a number
	    System.out.println("------Random Number Guessing Game------");
	    System.out.println(" - - Guess a number between 1 & 10 - -");
	    System.out.print("                  ");
	    
	    //using the scanner to get the input
	    inputNum = myScanner.nextInt();
	    
	    //printing the input number & the random number to test code
	    //System.out.println("\n" + inputNum);
	    //System.out.println("\n" + randomNum);
	    
	    // creating a while loop to continuously check for the right number
	    while(randomNum != inputNum)
	    {
	        //Prompting user again
	        System.out.println(" x x Sorry, wrong number. Try again x x");
	        System.out.print("                  ");
	        inputNum = myScanner.nextInt();
	    }
	    
	    //quick print statement to test the loop
        //System.out.print(":)");
        
        // once the user guesses the right number
        System.out.println("- - - - 😘  Have a nice day!! - - -");
	    System.out.println("✨ Yay! You guessed the right number! ✨");
        
        
        
    }
}





